# [stage 1: create image: interim:1.1]       # FROM nikolaik/python-nodejs:python3.8-nodejs15
# [stage 2: create image: req:1.1](ca.10min) # FROM interim:2.0
# [stage 3: create image: app:1.1]           # FROM req:2.0
FROM interim:2.0

# [stage 1: create image: interim:1.1] # 
WORKDIR /home/app
RUN apt-get update -y


# [stage 2: create image: req:1.1]     # 
ARG REQTXT=requirements.venv2.baseline.txt
COPY ./$REQTXT /home/app
#RUN pip install --no-use-wheel --allow-all-external -r $REQTXT
RUN unset -v PYTHONPATH
RUN pip install --upgrade -r $REQTXT
# [stage 3: create image: app:1.1]     # 
COPY . /home/app
COPY .env.appcontainer2dbcontainer .env
RUN npm install -g npm@7.12.0 --python=python3.8
# #RUN npm install --python=python3.8
EXPOSE 4000
CMD [ "npm", "start" ]